//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStart")]
    public interface IStart {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStart/TotalSpace", ReplyAction="http://tempuri.org/IStart/TotalSpaceResponse")]
        string TotalSpace(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStart/TotalSpace", ReplyAction="http://tempuri.org/IStart/TotalSpaceResponse")]
        System.Threading.Tasks.Task<string> TotalSpaceAsync(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStart/FreeSpace", ReplyAction="http://tempuri.org/IStart/FreeSpaceResponse")]
        string FreeSpace(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStart/FreeSpace", ReplyAction="http://tempuri.org/IStart/FreeSpaceResponse")]
        System.Threading.Tasks.Task<string> FreeSpaceAsync(string diskName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStartChannel : ProxyClient.ServiceReference1.IStart, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StartClient : System.ServiceModel.ClientBase<ProxyClient.ServiceReference1.IStart>, ProxyClient.ServiceReference1.IStart {
        
        public StartClient() {
        }
        
        public StartClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StartClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StartClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TotalSpace(string diskName) {
            return base.Channel.TotalSpace(diskName);
        }
        
        public System.Threading.Tasks.Task<string> TotalSpaceAsync(string diskName) {
            return base.Channel.TotalSpaceAsync(diskName);
        }
        
        public string FreeSpace(string diskName) {
            return base.Channel.FreeSpace(diskName);
        }
        
        public System.Threading.Tasks.Task<string> FreeSpaceAsync(string diskName) {
            return base.Channel.FreeSpaceAsync(diskName);
        }
    }
}
