//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Prices = new HashSet<Price>();
            this.WareHouseItems = new HashSet<WareHouseItem>();
        }
    
        public int Id { get; set; }
        public decimal Volume { get; set; }
        public int VolumeMeasureId { get; set; }
        public int MeasureId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Measure Measure { get; set; }
        public virtual Measure Measure1 { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<WareHouseItem> WareHouseItems { get; set; }
    }
}
