//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public WareHouse()
        {
            this.WareHouseItems = new HashSet<WareHouseItem>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<WareHouseItem> WareHouseItems { get; set; }
    }
}
