//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TablesFuel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AZS
    {
        public AZS()
        {
            this.Fuel = new HashSet<Fuel>();
        }
    
        public int id { get; set; }
        public int RegionId { get; set; }
        public string AZS_Name { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Fuel> Fuel { get; set; }
    }
}
