//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BStore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> OrderType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
