//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Activities = new HashSet<Activities>();
            this.Residence = new HashSet<Residence>();
            this.EatPlace = new HashSet<EatPlace>();
            this.Entertainment = new HashSet<Entertainment>();
            this.Supermarkets = new HashSet<Supermarkets>();
            this.Transport = new HashSet<Transport>();
        }
    
        public int Id { get; set; }
        public int CountryId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Activities> Activities { get; set; }
        public virtual ICollection<Residence> Residence { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<EatPlace> EatPlace { get; set; }
        public virtual ICollection<Entertainment> Entertainment { get; set; }
        public virtual ICollection<Supermarkets> Supermarkets { get; set; }
        public virtual ICollection<Transport> Transport { get; set; }
    }
}
